import type { Customer, ServiceOrder } from '@/types';

export const mockCustomers: Customer[] = [
  {
    id: 'CUST-001',
    name: 'VALDECIR ALVARINO',
    phone: '(11) 98765-4321',
    email: 'valdecir.alvarino@example.com',
    address: 'Rua das Flores, 123, São Paulo, SP',
    observations: 'Cliente prefere contato por WhatsApp.',
  },
  {
    id: 'CUST-002',
    name: 'CLIENTE AVULSO',
    phone: '(21) 91234-5678',
    email: 'cliente.avulso@example.com',
    address: 'Avenida Copacabana, 456, Rio de Janeiro, RJ',
    observations: '',
  },
  {
    id: 'CUST-003',
    name: 'CESTA BASICA SANTA RITA',
    phone: '(31) 99988-7766',
    email: 'santa.rita@example.com',
    address: 'Praça da Liberdade, 789, Belo Horizonte, MG',
    observations: 'Indicada por outro cliente.',
  },
  {
    id: 'CUST-004',
    name: 'Daniel Martins',
    phone: '(51) 98877-6655',
    email: 'daniel.martins@example.com',
    address: 'Rua dos Andradas, 101, Porto Alegre, RS',
    observations: 'Cliente antigo.',
  },
  {
    id: 'CUST-005',
    name: 'Eduarda Lima',
    phone: '(71) 97766-5544',
    email: 'eduarda.lima@example.com',
    address: 'Largo do Pelourinho, 202, Salvador, BA',
    observations: '',
  },
];

export const mockServiceOrders: ServiceOrder[] = [
    {
    id: 'OS-2024-3803',
    customerName: 'VALDECIR ALVARINO',
    equipment: 'IMPRESSORA EPSON L3150',
    reportedProblem: 'Não liga',
    status: 'Aberta',
    date: '2025-07-15',
    totalValue: 0,
  },
  {
    id: 'OS-2024-7318',
    customerName: 'VALDECIR ALVARINO',
    equipment: 'COMPUTADOR HP ALL IN ONE',
    reportedProblem: 'Tela quebrada',
    status: 'Aberta',
    date: '2025-07-15',
    totalValue: 850.0,
  },
  {
    id: 'OS-2024-7978',
    customerName: 'CLIENTE AVULSO',
    equipment: 'COMPUTADOR HP ALL IN ONE',
    reportedProblem: 'Não puxa papel',
    status: 'Aguardando Pagamento',
    date: '2025-07-15',
    totalValue: 120.0,
  },
  {
    id: 'OS-2024-4125',
    customerName: 'CESTA BASICA SANTA RITA',
    equipment: 'Notebook ACER ASPIRE 3',
    reportedProblem: 'Bateria não segura carga',
    status: 'Aguardando peça',
    date: '2025-07-14',
    totalValue: 350.0,
  },
  {
    id: 'OS-2024-005',
    customerName: 'Eduarda Lima',
    equipment: 'Macbook Air M1',
    reportedProblem: 'Teclado com falha em algumas teclas',
    status: 'Entregue',
    date: '2024-07-15',
    totalValue: 600.0,
  },
  {
    id: 'OS-2024-006',
    customerName: 'Daniel Martins',
    equipment: 'Desktop Gamer',
    reportedProblem: 'Superaquecendo e desligando',
    status: 'Recebido',
    date: '2024-07-21',
    totalValue: 0,
  },
];

export const mockRevenueData = [
    { month: 'Jan', revenue: 4000, expenses: 2400 },
    { month: 'Fev', revenue: 3000, expenses: 1398 },
    { month: 'Mar', revenue: 5000, expenses: 3800 },
    { month: 'Abr', revenue: 2780, expenses: 1908 },
    { month: 'Mai', revenue: 1890, expenses: 1800 },
    { month: 'Jun', revenue: 3390, expenses: 2500 },
    { month: 'Jul', revenue: 4490, expenses: 3100 },
]
