import type { Customer, ServiceOrder, StockItem } from '@/types';

export const mockCustomers: Customer[] = [
  {
    id: 'CUST-001',
    name: 'VALDECIR ALVARINO',
    phone: '(11) 98765-4321',
    email: 'valdecir.alvarino@example.com',
    address: 'Rua das Flores, 123, São Paulo, SP',
    observations: 'Cliente prefere contato por WhatsApp.',
  },
  {
    id: 'CUST-002',
    name: 'CLIENTE AVULSO',
    phone: '(21) 91234-5678',
    email: 'cliente.avulso@example.com',
    address: 'Avenida Copacabana, 456, Rio de Janeiro, RJ',
    observations: '',
  },
  {
    id: 'CUST-003',
    name: 'CESTA BASICA SANTA RITA',
    phone: '(31) 99988-7766',
    email: 'santa.rita@example.com',
    address: 'Praça da Liberdade, 789, Belo Horizonte, MG',
    observations: 'Indicada por outro cliente.',
  },
  {
    id: 'CUST-004',
    name: 'Daniel Martins',
    phone: '(51) 98877-6655',
    email: 'daniel.martins@example.com',
    address: 'Rua dos Andradas, 101, Porto Alegre, RS',
    observations: 'Cliente antigo.',
  },
  {
    id: 'CUST-005',
    name: 'Eduarda Lima',
    phone: '(71) 97766-5544',
    email: 'eduarda.lima@example.com',
    address: 'Largo do Pelourinho, 202, Salvador, BA',
    observations: '',
  },
    {
    id: 'CUST-006',
    name: 'Ana Costa',
    phone: '(81) 96655-4433',
    email: 'ana.costa@example.com',
    address: 'Rua da Aurora, 303, Recife, PE',
    observations: '',
  },
  {
    id: 'CUST-007',
    name: 'Carlos Mendes',
    phone: '(92) 95544-3322',
    email: 'carlos.mendes@example.com',
    address: 'Avenida Eduardo Ribeiro, 404, Manaus, AM',
    observations: 'Prefere pagamento em dinheiro.',
  },
];

export const mockServiceOrders: ServiceOrder[] = [
    {
    id: 'OS-2024-3803',
    customerName: 'VALDECIR ALVARINO',
    equipment: 'IMPRESSORA EPSON L3150',
    serialNumber: 'ABC12345',
    accessories: 'Cabo de força',
    reportedProblem: 'NAO IMPRIME',
    technicalReport: 'Necessário limpeza do cabeçote de impressão e substituição do cartucho preto.',
    status: 'Aberta',
    date: '2025-07-17',
    totalValue: 150,
    items: [{ id: 1, description: 'Limpeza de cabeçote', quantity: 1, unitPrice: 150, type: 'service' }],
    attendant: 'João Silva',
    paymentMethod: 'Pendente',
    warranty: '90 dias para o serviço',
  },
  {
    id: 'OS-2024-7318',
    customerName: 'VALDECIR ALVARINO',
    equipment: 'COMPUTADOR HP',
    reportedProblem: 'NAO ENTRA NO WINDOS',
    status: 'Aberta',
    date: '2025-07-17',
    totalValue: 0,
    items: [],
    attendant: 'Maria Oliveira',
    paymentMethod: 'Pendente',
  },
  {
    id: 'OS-2024-7978',
    customerName: 'CLIENTE AVULSO',
    equipment: 'COMPUTADOR HP',
    reportedProblem: 'LENTO NAO ENTRA',
    status: 'Aguardando',
    date: '2025-07-16',
    totalValue: 120.0,
    items: [{ id: 1, description: 'Formatação e Reinstalação do Windows', quantity: 1, unitPrice: 120, type: 'service' }],
    attendant: 'João Silva',
    paymentMethod: 'Pendente',
    warranty: 'Serviço sem garantia',
  },
  {
    id: 'OS-2024-4125',
    customerName: 'CESTA BASICA SANTA RITA',
    equipment: 'Notebook ACER ASPIRE 3',
    serialNumber: 'SN98765B',
    accessories: 'Fonte original',
    reportedProblem: 'Bateria não segura carga',
    technicalReport: 'Bateria com desgaste natural. Substituição recomendada.',
    status: 'Aguardando peça',
    date: '2025-07-14',
    totalValue: 350.0,
    items: [
      { id: 1, description: 'Bateria para Acer Aspire 3', quantity: 1, unitPrice: 280, type: 'part' },
      { id: 2, description: 'Mão de obra para troca', quantity: 1, unitPrice: 70, type: 'service' },
    ],
    attendant: 'Pedro Martins',
    paymentMethod: 'Pendente',
    warranty: '1 ano para a peça, 90 dias para o serviço',
  },
  {
    id: 'OS-2024-005',
    customerName: 'Eduarda Lima',
    equipment: 'Macbook Air M1',
    serialNumber: 'SNM1BCA8',
    accessories: 'Nenhum',
    reportedProblem: 'Teclado com falha em algumas teclas',
    technicalReport: 'Realizada a troca do top-case (teclado e carcaça superior).',
    status: 'Entregue',
    date: '2024-07-15',
    totalValue: 600.0,
    items: [{ id: 1, description: 'Troca do top-case (teclado)', quantity: 1, unitPrice: 600, type: 'service' }],
    attendant: 'Ana Beatriz',
    paymentMethod: 'Cartão de Crédito',
    warranty: '90 dias para o serviço',
  },
  {
    id: 'OS-2024-006',
    customerName: 'Daniel Martins',
    equipment: 'Desktop Gamer',
    serialNumber: 'SN-GAMER-X1',
    accessories: 'Cabo de força',
    reportedProblem: 'Superaquecendo e desligando em jogos',
    technicalReport: 'Limpeza interna completa, troca da pasta térmica do processador e da placa de vídeo. Temperaturas normalizadas.',
    status: 'Finalizado',
    date: '2024-07-21',
    totalValue: 250,
    items: [
        { id: 1, description: 'Limpeza interna completa e troca de pasta térmica', quantity: 1, unitPrice: 250, type: 'service' }
    ],
    attendant: 'Carlos Souza',
    paymentMethod: 'PIX',
    warranty: '90 dias para o serviço',
  },
];

export const mockRevenueData = [
    { month: 'Jan', revenue: 4000, expenses: 2400 },
    { month: 'Fev', revenue: 3000, expenses: 1398 },
    { month: 'Mar', revenue: 5000, expenses: 3800 },
    { month: 'Abr', revenue: 2780, expenses: 1908 },
    { month: 'Mai', revenue: 1890, expenses: 1800 },
    { month: 'Jun', revenue: 3390, expenses: 2500 },
    { month: 'Jul', revenue: 4490, expenses: 3100 },
];


export const mockStock: StockItem[] = [
  { id: 'SSD-KNG-240', name: 'SSD 240GB Kingston', quantity: 8, price: 180.00, category: 'Armazenamento', unitOfMeasure: 'UN', minStock: 3, costPrice: 130.00, barcode: 'PROD-1721935634515' },
  { id: 'MEM-DDR4-8GB', name: 'Memória RAM 8GB DDR4 Notebook', quantity: 12, price: 220.00, category: 'Componentes', unitOfMeasure: 'UN', minStock: 5, costPrice: 170.00, barcode: 'PROD-1721935634516' },
  { id: 'BATT-ACR-A3', name: 'Bateria para Acer Aspire 3', quantity: 4, price: 280.00, category: 'Baterias', unitOfMeasure: 'UN', minStock: 2, costPrice: 210.00, barcode: 'PROD-1721935634517' },
  { id: 'SCR-156-SLIM', name: 'Tela 15.6" LED Slim', quantity: 10, price: 350.00, category: 'Telas', unitOfMeasure: 'UN', minStock: 3, costPrice: 290.00, barcode: 'PROD-1721935634518' },
  { id: 'KB-DLL-INSP', name: 'Teclado ABNT2 Dell Inspiron', quantity: 1, price: 120.00, category: 'Teclados', unitOfMeasure: 'UN', minStock: 2, costPrice: 85.00, barcode: 'PROD-1721935634519' },
  { id: 'FNT-UNIV-NB', name: 'Fonte Carregador Universal Notebook', quantity: 0, price: 90.00, category: 'Fontes', unitOfMeasure: 'UN', minStock: 3, costPrice: 65.00, barcode: 'PROD-1721935634520' },
  { id: 'PAST-TERM-5G', name: 'Pasta Térmica Prata 5g', quantity: 20, price: 25.00, category: 'Insumos', unitOfMeasure: 'UN', minStock: 10, costPrice: 15.00, barcode: 'PROD-1721935634521' },
];
